version: '3.7'

services:
  nginx:
    restart: always
    build:
      context: nginx
    ports:
      - "80:80"
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - canalservice-db:/var/lib/postgresql/data
  canalservice:
    build:
      context: app
      dockerfile: Dockerfile
      target: base
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: postgres
      PORT: 5000
    depends_on:
      - postgres
    volumes:
      - ./app/src:/home/node/app/src
      - ./app/nodemon.json:/home/node/app/nodemon.json
    container_name: canalservice
    expose:
      - '5000'
    ports:
      - '5000:5000'
    command: npm run start:dev

volumes:
  canalservice-db:
